
#define PI 3.14159265
#define BUFFERSIZE 3000
#define FREQUENCY 440.0
#define CSFIFOSIZE 5000
#define DELAYMAX 100100

#define STB_X 60
#define STB_Y 70
#define TONE_OFFSET 67

#define ADSR_TRANSL_X 0
#define ADSR_TRANSL_Y -15


#define SQUARE_WAVE 1
#define SAWTOOTH_WAVE 2
#define SINE_WAVE 3
#define N2_WAVE 4
#define N3_WAVE 5
#define ORGAN_WAVE 6
#define N05_WAVE 7
#define STAIRS_3STEPS 8


#define IDC_LIST 30
#define ID_BUTTON_SAVE 31
#define ID_EDIT_FILENAME 32
#define ID_BUTTON_EXPORTNOW 33
#define ID_BUTTON_MIDIIN 34
#define IDC_LIST2 35
#define ID_BUTTON_MIDICANCEL 36
#define ID_BUTTON_MIDISELECT 37
#define ID_BUTTON_SEQUENCE 38
#define ID_TIMER1 39
#define ID_BUTTON_PLAY 40
#define ID_BUTTON_TONELENGTH_DEC 41
#define ID_BUTTON_TONELENGTH_INC 42
#define ID_BUTTON_BPM_DEC 43
#define ID_BUTTON_BPM_INC 44
#define ID_BUTTON_REVERB 45
#define ID_BUTTON_VIBRATO 46
#define ID_BUTTON_TONE_INC 47
#define ID_BUTTON_TONE_DEC 48
#define ID_BUTTON_TIME_INC 49
#define ID_BUTTON_TIME_DEC 50
#define ID_BUTTON_TIMEMAX_DEC 51
#define ID_BUTTON_TIMEMAX_INC 52
#define ID_BUTTON_REV_ONOFF 53
#define ID_BUTTON_REV_INFOOUT 54
#define ID_BUTTON_REV_SETSTANDARD 55
#define ID_BUTTON_ABOUT 56

#define REV_EARLY_BOUNCE_X 20
#define REV_EARLY_BOUNCE_Y 30
#define REV_BOUNCE_X 20
#define REV_BOUNCE_Y 280
#define REV_DEPTH_X 360
#define REV_DEPTH_Y 30
#define REV_WINDOWSIZE_X 660
#define REV_WINDOWSIZE_Y 550
